language: php

sudo: false

php:
  - 7.3

env:
  matrix:
    - LARAVEL=5.8.*

matrix:
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)