language: php

sudo: false

php:
  - 7.3

env:
  matrix:
    - LARAVEL=5.8.*

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

#install:
#  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose